// <auto-generated />
using System;
using ApiAgroFin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiAgroFin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiAgroFin.Models.Endereco", b =>
                {
                    b.Property<int>("Endereco_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Endereco_Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco_Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco_Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco_Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco_Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Endereco_Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Endereco_Numero")
                        .HasColumnType("int");

                    b.Property<int?>("Pessoa_Id")
                        .HasColumnType("int");

                    b.HasKey("Endereco_Id");

                    b.HasIndex("Pessoa_Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("ApiAgroFin.Models.Pagador", b =>
                {
                    b.Property<int>("Pagador_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pessoa_Id")
                        .HasColumnType("int");

                    b.HasKey("Pagador_Id");

                    b.HasIndex("Pessoa_Id");

                    b.ToTable("Pagador");
                });

            modelBuilder.Entity("ApiAgroFin.Models.Pessoa", b =>
                {
                    b.Property<int>("Pessoa_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pessoa_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pessoa_Numero_Identificador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pessoa_Id");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("ApiAgroFin.Models.Recebedor", b =>
                {
                    b.Property<int>("Recebedor_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pessoa_Id")
                        .HasColumnType("int");

                    b.HasKey("Recebedor_Id");

                    b.HasIndex("Pessoa_Id");

                    b.ToTable("Recebedor");
                });

            modelBuilder.Entity("ApiAgroFin.Models.Titulo", b =>
                {
                    b.Property<int>("Titulo_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Pagador_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Recebedor_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Titulo_Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo_Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo_Status")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<double>("Titulo_Valor")
                        .HasColumnType("float");

                    b.Property<string>("Titulo_Valor_Extenso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Titulo_Id");

                    b.HasIndex("Pagador_Id");

                    b.HasIndex("Recebedor_Id");

                    b.ToTable("Titulo");
                });

            modelBuilder.Entity("ApiAgroFin.Models.Endereco", b =>
                {
                    b.HasOne("ApiAgroFin.Models.Pessoa", "pessoa")
                        .WithMany("Enderecos")
                        .HasForeignKey("Pessoa_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("pessoa");
                });

            modelBuilder.Entity("ApiAgroFin.Models.Pagador", b =>
                {
                    b.HasOne("ApiAgroFin.Models.Pessoa", "Pessoa")
                        .WithMany("Pagadores")
                        .HasForeignKey("Pessoa_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ApiAgroFin.Models.Recebedor", b =>
                {
                    b.HasOne("ApiAgroFin.Models.Pessoa", "Pessoa")
                        .WithMany("Recebedores")
                        .HasForeignKey("Pessoa_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ApiAgroFin.Models.Titulo", b =>
                {
                    b.HasOne("ApiAgroFin.Models.Pagador", "Pagador")
                        .WithMany()
                        .HasForeignKey("Pagador_Id");

                    b.HasOne("ApiAgroFin.Models.Recebedor", "Recebedor")
                        .WithMany()
                        .HasForeignKey("Recebedor_Id");

                    b.Navigation("Pagador");

                    b.Navigation("Recebedor");
                });

            modelBuilder.Entity("ApiAgroFin.Models.Pessoa", b =>
                {
                    b.Navigation("Enderecos");

                    b.Navigation("Pagadores");

                    b.Navigation("Recebedores");
                });
#pragma warning restore 612, 618
        }
    }
}
